=== quangvu482001/XLM_PHP/Tailieu/bai5/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<xsd:element name="books">
<xsd:complexType>
<xsd:sequence>
<xsd:element name="book" type="BookType" maxOccurs="unbounded"/>
</xsd:sequence>
</xsd:complexType>
</xsd:element>

<xsd:complexType name="BookType">
<xsd:sequence>
<xsd:element name="author" type="xsd: string"/>
<xsd:element name="title" type="titleType"/>
<xsd:element name="edition" type="xsd: byte"/>
</xsd:sequence>
<xsd:asstribute name="idbn" type="xsd: string" use="required"/>
</xsd:complexType>

<xsd:complexType name="titleType">
    <xsd:simpleContent>
        <xsd:extension base="xsd: string">
        <xsd:attribute base="xsd: string">
            <xsd:attribute name="type" use="required"/>
            <xsd:simpleType>
                <xsd:restriction base="xsd: string">
                    <xsd:enumeration value="P"/>
                    <xsd:enumeration value="H"/>
                </xsd:restriction>
            </xsd:simpleType>
        </xsd:attribute>
        </xsd:extension>
    </xsd:simpleContent>
</xsd:complexType>
</xsd:schema>

=== quangvu482001/XLM_PHP/Tailieu/bai5/giai_C5.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"  xs:noNamespaceSchemaLocation="book.xsd">
    <book idbn="12">
        <author>Nguyen Van A</author>
        <title type="P">C++</title>
        <edition>1</edition>
    </book>
    <book idbn="13">
        <author>Nguyen Van B</author>
        <title type="P">Java</title>
        <edition>2</edition>
    </book>
</books>
